from database import Base, engine, get_db
from models.property import Property
from sqlalchemy.orm import Session
import json

Base.metadata.create_all(bind=engine)

db: Session = next(get_db())

properties = [
    Property(
        title="Dúplex con piscina en Roquetas de Mar",
        slug="duplex-piscina-roquetas-mar",
        price=320000,
        operation="venta",
        property_type="chalet",
        bedrooms=4,
        bathrooms=3,
        surface=165,
        location="Roquetas de Mar",
        address="Av. de la Playa, 22, Roquetas de Mar",
        description="Este dúplex en primera línea de Roquetas es una joya. Planta baja con salón enorme, cocina independiente y un patio que da directamente a la piscina. Arriba, cuatro dormitorios con armarios empotrados y dos baños completos. Urbanización con vigilancia, piscina grande y jardines cuidados. Está a dos minutos andando de la playa y al lado del paseo marítimo. Ideal para familia que quiera vivir en la costa con todas las comodidades.",
        features="Piscina comunitaria,Patio,Garaje,Trastero,Armarios empotrados,Aire acondicionado,Urbanización cerrada,Zona comunitaria",
        latitude=36.7740,
        longitude=-2.6140,
        status="disponible",
        featured=True,
        images="/static/images/image00036.jpeg,/static/images/image00035.jpeg",
    ),
    Property(
        title="Garaje en Huércal de Almería",
        slug="garaje-huercal-almeria",
        price=18000,
        operation="venta",
        property_type="garaje",
        bedrooms=0,
        bathrooms=0,
        surface=12,
        location="Huércal de Almería",
        address="C. Río Júcar, 2",
        description="Vendo mi plaza de garaje en el centro de Huércal. Cabe un coche grande sin problema, está limpia y tiene fácil maniobra. El edificio tiene seguridad y la puerta automática funciona perfectamente. Aprovecha que en esta zona aparcar en la calle es misión imposible.",
        features="Plaza grande,Puerta automática,Buena maniobra",
        latitude=36.8835,
        longitude=-2.4405,
        status="disponible",
        featured=False,
        images="/static/images/image00034.jpeg",
    ),
    Property(
        title="Piso luminoso cerca de la Rambla, Almería capital",
        slug="piso-rambla-almeria-capital",
        price=189000,
        operation="venta",
        property_type="piso",
        bedrooms=3,
        bathrooms=2,
        surface=95,
        location="Centro, Almería",
        address="Av. de la Rambla, 15",
        description="Piso en una de las mejores zonas de Almería capital, a dos pasos de la Rambla y del Puerto. Todo reformado con mucho gusto: cocina abierta al salón, suelos de madera, ventanas de doble acristalamiento y persianas eléctricas. Tres dormitorios amplios, el principal con baño en suite. Perfecto para profesionales o parejas que quieran vivir en el centro sin renunciar al confort.",
        features="Cocina abierta,Suelo de madera,Doble acristalamiento,Persianas eléctricas,Baño en suite,Aire acondicionado,Ascensor",
        latitude=36.8385,
        longitude=-2.4640,
        status="disponible",
        featured=True,
        images="/static/images/hero-bg.jpg,/static/images/image00049.jpeg",
    ),
    Property(
        title="Cortijo rural en Almería — Sierra de Gádor",
        slug="cortijo-rural-sierra-gador",
        price=185000,
        operation="venta",
        property_type="casa",
        bedrooms=3,
        bathrooms=1,
        surface=120,
        location="Sierra de Gádor, Almería",
        address="Paraje Los Llanos, s/n",
        description="A solo 25 minutos de la capital, este cortijo tiene el encanto de la Almería más auténtica. Casa de pueblo reformada manteniendo la esencia: vigas de madera vistas, paredes de piedra y un porche ideal para las comidas de verano. Tiene agua de pozo, terreno alrededor y unas vistas espectaculares de la sierra. No temáis a la carretera — está asfaltada y en buen estado. Ideal para fin de semana, teletrabajo o casa rural vacacional.",
        features="Chimenea,Porche,Terreno,Vistas a la montaña,Agua de pozo,Reformada",
        latitude=36.9000,
        longitude=-2.8000,
        status="disponible",
        featured=False,
        images="/static/images/image00050.jpeg,/static/images/image00036.jpeg",
    ),
    Property(
        title="Piso reformado en Huércal de Almería",
        slug="piso-reformado-huercal-almeria",
        price=165000,
        operation="venta",
        property_type="piso",
        bedrooms=3,
        bathrooms=2,
        surface=90,
        location="Huércal de Almería",
        address="C. Río Júcar, 17",
        description="Vivo al ladito, conozco esta casa como si fuera mía. Tiene una luz increíble por la tarde, los vecinos son tranquilos y está a cinco minutos andando del Mercadona y del cole. La reforma la hicimos con materiales buenos de verdad, no te vas a encontrar sorpresas. Ideal para una familia que quiera sentar la cabeza sin dejarse un riñón.",
        features="Cocina equipada,Aire acondicionado,Armarios empotrados,Suelo porcelánico,Ascensor",
        latitude=36.8820,
        longitude=-2.4390,
        status="disponible",
        featured=True,
        images="/static/images/image00034.jpeg,/static/images/image00035.jpeg,/static/images/hero-bg.jpg",
    ),
    Property(
        title="Ático con terraza en Aguadulce",
        slug="atico-terraza-aguadulce",
        price=275000,
        operation="venta",
        property_type="ático",
        bedrooms=2,
        bathrooms=1,
        surface=68,
        location="Aguadulce, Almería",
        address="Paseo Marítimo de Aguadulce, 12",
        description="Este ático es una pasada. La terraza es lo mejor — 35 metros con vistas al mar, perfecta para cenar en verano o tomarte un café viendo el amanecer. Lo tiene todo: cocina abierta, dormitorios grandes y un baño completo reformado. Vivo en la zona y te aseguro que no vas a encontrar otro así por este precio.",
        features="Terraza,Vistas al mar,Aire acondicionado,Plaza de garaje,Armarios empotrados",
        latitude=36.8158,
        longitude=-2.5635,
        status="disponible",
        featured=True,
        images="/static/images/image00036.jpeg,/static/images/image00049.jpeg",
    ),
    Property(
        title="Local comercial en el centro de Almería",
        slug="local-comercial-centro-almeria",
        price=1500,
        operation="alquiler",
        property_type="local",
        bedrooms=0,
        bathrooms=1,
        surface=110,
        location="Centro, Almería",
        address="C. de las Tiendas, 5",
        description="Llevo años pateándome estas calles y te digo: este local tiene un paso de gente increíble. Perfecto para una cafetería, una tienda de ropa o lo que quieras montar. Tiene el escaparate grande, el aire ya puesto y un almacén detrás que viene de lujo. El dueño anterior se jubiló, pero el local está como una patena.",
        features="Escaparate,Aire acondicionado,Aseo,Almacén",
        latitude=36.8380,
        longitude=-2.4580,
        status="disponible",
        featured=False,
        images="/static/images/image00034.jpeg",
    ),
    Property(
        title="Casa con jardín en El Alquián",
        slug="casa-jardin-el-alquian",
        price=395000,
        operation="venta",
        property_type="casa",
        bedrooms=4,
        bathrooms=2,
        surface=140,
        location="El Alquián, Almería",
        address="C. Granada, 28",
        description="Esta casa tiene algo especial. El jardín es pequeño pero acogedor — da el sol todo el día y se oyen los pájaros por la mañana. Está en una calle tranquila pero cerca de todo: supermercado, parada de bus y el cole. La construyeron bien, con materiales de calidad. Viene con garaje y trastero. Si te gusta tener tu espacio sin estar aislado, esta es tu casa.",
        features="Jardín,Piscima,Chimenea,Garaje,Trastero",
        latitude=36.8620,
        longitude=-2.4280,
        status="disponible",
        featured=True,
        images="/static/images/image00035.jpeg,/static/images/image00036.jpeg",
    ),
    Property(
        title="Estudio en Huércal de Almería",
        slug="estudio-huercal-almeria",
        price=475,
        operation="alquiler",
        property_type="piso",
        bedrooms=1,
        bathrooms=1,
        surface=32,
        location="Huércal de Almería",
        address="Av. de la Libertad, 4",
        description="Este estudio lo tiene todo para empezar. Lo reformamos entero hace un año y quedó muy apañado: cocina americana con encimera de silestone, plato de ducha grande, y un armario empotrado que coge más de lo que parece. Está al lado de la parada de bus y del centro comercial. Ideal para una persona que trabaje o estudie por la zona.",
        features="Amueblado,Cocina americana,Aire acondicionado,Armario empotrado",
        latitude=36.8830,
        longitude=-2.4420,
        status="disponible",
        featured=False,
        images="/static/images/image00034.jpeg",
    ),
    Property(
        title="Oficina en Huércal de Almería — Edificio Río Júcar",
        slug="oficina-edificio-rio-jucar",
        price=1600,
        operation="alquiler",
        property_type="local",
        bedrooms=0,
        bathrooms=2,
        surface=180,
        location="Huércal de Almería",
        address="C. Río Júcar, 17",
        description="Esta oficina está en el mismo edificio donde trabajamos nosotros, así que la conozco bien. Es diáfana, con mucha luz natural y vistas — sin edificios delante que te tapen. Tiene dos baños, aire centralizado y parking para los clientes. Perfecta para una gestoría, una clínica o cualquier negocio que quiera buena imagen y estar bien comunicado.",
        features="Aire acondicionado central,Ascensor,Plaza de garaje,Luz natural,Diáfana",
        latitude=36.8825,
        longitude=-2.4385,
        status="disponible",
        featured=False,
        images="/static/images/image00049.jpeg,/static/images/image00050.jpeg",
    ),
    Property(
        title="Piso en Calle la Gabriela, Aguadulce",
        slug="piso-calle-gabriela-aguadulce",
        price=258000,
        operation="venta",
        property_type="piso",
        bedrooms=3,
        bathrooms=2,
        surface=142,
        location="Aguadulce, Roquetas de Mar",
        address="Calle la Gabriela, 38",
        description="Te presentamos este fantástico piso a solo 3 minutos andando de la playa, ideal tanto como vivienda habitual como inversión vacacional. Cuenta con 3 amplias habitaciones, 2 baños completos, un luminoso salón-comedor con salida directa a una gran terraza con vistas despejadas a la piscina y al mar. La cocina está totalmente equipada, lista para entrar a vivir, y además dispone de un balcón interior. Ubicado en una zona tranquila y bien cuidada, combina comodidad, luminosidad y excelente ubicación junto al mar.",
        features="Terraza,Balcón,Armarios empotrados,Aire acondicionado,Piscina,Ascensor,Acceso adaptado,Orientación sur",
        latitude=36.7954,
        longitude=-2.5860,
        status="disponible",
        featured=True,
        images="/static/images/hero-bg.jpg",
    ),
]

for p in properties:
    exists = db.query(Property).filter(Property.slug == p.slug).first()
    if not exists:
        db.add(p)

db.commit()
db.close()
print("Seeded", len(properties), "properties")
